WITH WALLETS_CRYPTO AS
	(SELECT OWNER_ID,
			WALLET_ID,
			NAME
		FROM WALLETS
		JOIN CRYPTOCURRENCIES 
	 ON WALLETS.CRYPTO_ID = CRYPTOCURRENCIES.CRYPTO_ID)
SELECT TRANSACTION_ID,
	FILL,
	SRC_WALLET.NAME,
	SRC_WALLET.OWNER_ID,
	DST_WALLET.OWNER_ID
FROM TRANSACTIONS
JOIN WALLETS_CRYPTO AS SRC_WALLET 
ON TRANSACTIONS.SOURCE_WALLET_ID = SRC_WALLET.WALLET_ID
JOIN WALLETS_CRYPTO AS DST_WALLET 
ON TRANSACTIONS.DESTINATION_WALLET_ID = DST_WALLET.WALLET_ID
WHERE SRC_WALLET.OWNER_ID = 2
	OR DST_WALLET.OWNER_ID = 2